import { NextResponse } from 'next/server'
import { createClient } from '@/lib/supabase-server'
import { requireOperator } from '@/lib/operator'
import { isTimeframe, timeframeSince, type Timeframe } from '@/lib/analytics'
import { buildRewardAnalytics } from '@/lib/economy-rewards'

// Cap on windowed ledger rows fed into analytics — plenty for the breakdown +
// trend while keeping the response bounded on busy economies.
const WINDOW_ROW_LIMIT = 8000

/**
 * GET /api/guilds/[guildId]/economy/rewards?timeframe=24h|7d|30d|all
 *
 * The Earning view's analytics: coins generated by reward sources in the
 * window, payout counts, per-source breakdown ("most valuable activities"),
 * top earners and a generation trend. OPERATOR-ONLY — it backs the operator's
 * Earnings settings page (earning feeds the global economy). Only THIS guild's
 * reward payouts count (rows are attributed by guild_id), so the breakdown
 * reflects what this server's earning config is actually minting.
 */
export async function GET(
  req: Request,
  { params }: { params: Promise<{ guildId: string }> },
) {
  const { guildId } = await params
  const auth = await requireOperator()
  if (!auth.ok) return NextResponse.json({ error: auth.error }, { status: 403 })

  const supabase = await createClient()
  const tfParam = new URL(req.url).searchParams.get('timeframe')
  const timeframe: Timeframe = isTimeframe(tfParam) ? tfParam : '30d'
  const since = timeframeSince(timeframe)

  let q = supabase
    .from('economy_transactions')
    .select('user_id, user_name, amount, reason, created_at')
    .eq('guild_id', guildId)
    .gt('amount', 0)
    .order('created_at', { ascending: false })
    .limit(WINDOW_ROW_LIMIT)
  if (since) q = q.gte('created_at', since)

  const { data, error } = await q
  if (error) return NextResponse.json({ error: 'Failed to load analytics.' }, { status: 500 })

  const analytics = buildRewardAnalytics(data ?? [], timeframe)
  return NextResponse.json({ timeframe, analytics })
}
